package constant

import ()

const (
	OTA_ROOT              = "/home/jianmin/OTA/"
	RELEASE_ROOT          = OTA_ROOT + "release/"
	CP_RELEASE_ROOT       = RELEASE_ROOT + "CP/"
	CP_SERVER_MIRROR_ROOT = CP_RELEASE_ROOT + "CP_SERVER_MIRROR/"
	LOGS_ROOT             = OTA_ROOT + "logs/"

	HL_ROOT        = CP_SERVER_MIRROR_ROOT + "HL/"
	HL_DSDS_ROOT   = CP_SERVER_MIRROR_ROOT + "HL_DSDS/"
	LTE_ROOT       = CP_SERVER_MIRROR_ROOT + "LTE/"
	HLWB_ROOT      = HL_ROOT + "HLWB"
	HLWB_DSDS_ROOT = HL_DSDS_ROOT + "HLWB_DSDS"
	HLTD_ROOT      = HL_ROOT + "HLTD"
	HLTD_DSDS_ROOT = HL_DSDS_ROOT + "HLTD_DSDS"
	LTG_ROOT       = LTE_ROOT + "LTG"
	LWG_ROOT       = LTE_ROOT + "LWG"

	SCRIPTS_ROOT = OTA_ROOT + "scripts/"
	FILTER_ROOT  = SCRIPTS_ROOT + "filter/"
)

const (
	TABLE_ARBI = "arbi"
	TABLE_GRBI = "grbi"
	TABLE_RFIC = "rfic"
	TABLE_CP   = "cp_release"
)

const (
	SIM_SINGLE = "SINGLE"
	SIM_DSDS   = "DSDS"
	SIM_DSDA   = "DSDA"

	MODE_HLWB      = "HLWB"
	MODE_HLWB_DSDS = "HLWB_DSDS"
	MODE_HLTD      = "HLTD"
	MODE_HLTD_DSDS = "HLTD_DSDS"
	MODE_LTG       = "LTG"
	MODE_LWG       = "LWG"

	NETWORK_TD  = "TG"
	NETWORK_WB  = "WG"
	NETWORK_LTG = "LTG"
	NETWORK_LWG = "LWG"

	DROPPED_FLAG   = -1
	AVAILABLE_FLAG = 1
	DISABLE_FLAG   = 2
)

var (
	PATH_TO_MODE = map[string]string{
		HLWB_ROOT:      MODE_HLWB,
		HLWB_DSDS_ROOT: MODE_HLWB_DSDS,
		HLTD_ROOT:      MODE_HLTD,
		HLTD_DSDS_ROOT: MODE_HLTD_DSDS,
		LTG_ROOT:       MODE_LTG,
		LWG_ROOT:       MODE_LWG,
	}
	MODE_TO_SIM = map[string]string{
		MODE_HLWB:      SIM_SINGLE,
		MODE_HLTD:      SIM_SINGLE,
		MODE_HLWB_DSDS: SIM_DSDS,
		MODE_HLTD_DSDS: SIM_DSDS,
		MODE_LTG:       SIM_SINGLE,
		MODE_LWG:       SIM_SINGLE,
	}
	MODE_TO_NETWORK = map[string]string{
		MODE_HLWB:      NETWORK_WB,
		MODE_HLTD:      NETWORK_TD,
		MODE_HLWB_DSDS: NETWORK_WB,
		MODE_HLTD_DSDS: NETWORK_TD,
		MODE_LTG:       NETWORK_LTG,
		MODE_LWG:       NETWORK_LWG,
	}
	MODE_TO_PREFIX_LEN = map[string]int{
		MODE_HLWB:      len(HL_ROOT),
		MODE_HLTD:      len(HL_ROOT),
		MODE_HLWB_DSDS: len(HL_DSDS_ROOT),
		MODE_HLTD_DSDS: len(HL_DSDS_ROOT),
		MODE_LTG:       len(LTE_ROOT),
		MODE_LWG:       len(LTE_ROOT),
	}
	MODE_TO_ROOT_PATH = map[string]string{
		MODE_HLWB:      HL_ROOT,
		MODE_HLTD:      HL_ROOT,
		MODE_HLWB_DSDS: HL_DSDS_ROOT,
		MODE_HLTD_DSDS: HL_DSDS_ROOT,
		MODE_LTG:       LTE_ROOT,
		MODE_LWG:       LTE_ROOT,
	}

	SIM_LIST     = []string{SIM_SINGLE, SIM_DSDS, SIM_DSDA}
	NETWORK_LIST = []string{NETWORK_LWG, NETWORK_LTG, NETWORK_TD, NETWORK_WB}
	FLAG_LIST    = []int{DROPPED_FLAG, AVAILABLE_FLAG, DISABLE_FLAG}
)
