package constant

import ()

const (
	OTA_ROOT        = "/home/manson/OTA/"
	CP_RELEASE_ROOT = OTA_ROOT + "release/CP/CP_SERVER_MIRROR/"
	LOGS_ROOT       = OTA_ROOT + "logs/"

	HL_ROOT      = CP_RELEASE_ROOT + "HL/"
	HL_DSDS_ROOT = CP_RELEASE_ROOT + "HL_DSDS/"
	LTE_ROOT     = CP_RELEASE_ROOT + "LTE/"

	HLWB_ROOT      = HL_ROOT + "HLWB"
	HLWB_DSDS_ROOT = HL_DSDS_ROOT + "HLWB_DSDS"
	HLTD_ROOT      = HL_ROOT + "HLTD"
	HLTD_DSDS_ROOT = HL_DSDS_ROOT + "HLTD_DSDS"
	LTG_ROOT       = LTE_ROOT + "LTG"
	LWG_ROOT       = LTE_ROOT + "LWG"

	MONITOR_COUNT = 5
)

const (
	TABLE_ARBI = "arbi"
	TABLE_GRBI = "grbi"
	TABLE_RFIC = "rfic"
	TABLE_CP   = "cp_release"
)

const (
	SIM_SINGLE = "SINGLE"
	SIM_DSDS   = "DSDS"
	SIM_DSDA   = "DSDA"

	MODE_HLWB      = "HLWB"
	MODE_HLWB_DSDS = "HLWB_DSDS"
	MODE_HLTD      = "HLTD"
	MODE_HLTD_DSDS = "HLTD_DSDS"
	MODE_LTG       = "LTG"
	MODE_LWG       = "LWG"

	NETWORK_TD  = "TG"
	NETWORK_WB  = "WG"
	NETWORK_LTE = "LTG"

	PLATFORM_1088 = "HELAN"
	PLATFORM_1L88 = "HELANLTE"

	PRODUCT_HELAN    = "pxa1088dkb"
	PRODUCT_HELANLTE = "pxa1L88dkb"

	MODEL_1088 = "pxa1088ff_def"
	MODEL_1T88 = "pxa1t88ff_def"
	MODEL_1L88 = "pxa1l88ff_def"

	DEVICE_FF  = "FF"
	DEVICE_DKB = "DKB"

	DROPPED_FLAG   = -1
	AVAILABLE_FLAG = 1
	DISABLE_FLAG   = 2
)

var (
	PATH_TO_MODE = map[string]string{
		HLWB_ROOT:      MODE_HLWB,
		HLWB_DSDS_ROOT: MODE_HLWB_DSDS,
		HLTD_ROOT:      MODE_HLTD,
		HLTD_DSDS_ROOT: MODE_HLTD_DSDS,
		LTG_ROOT:       MODE_LTG,
		LWG_ROOT:       MODE_LWG,
	}
	MODE_TO_SIM = map[string]string{
		MODE_HLWB:      SIM_SINGLE,
		MODE_HLTD:      SIM_SINGLE,
		MODE_HLWB_DSDS: SIM_DSDS,
		MODE_HLTD_DSDS: SIM_DSDS,
		MODE_LTG:       SIM_SINGLE,
		MODE_LWG:       SIM_SINGLE,
	}
	MODE_TO_NETWORK = map[string]string{
		MODE_HLWB:      NETWORK_WB,
		MODE_HLTD:      NETWORK_TD,
		MODE_HLWB_DSDS: NETWORK_WB,
		MODE_HLTD_DSDS: NETWORK_TD,
		MODE_LTG:       NETWORK_LTE,
		MODE_LWG:       NETWORK_LTE,
	}
	MODE_TO_PLATFORM = map[string]string{
		MODE_HLWB:      PLATFORM_1088,
		MODE_HLTD:      PLATFORM_1088,
		MODE_HLWB_DSDS: PLATFORM_1088,
		MODE_HLTD_DSDS: PLATFORM_1088,
		MODE_LTG:       PLATFORM_1L88,
		MODE_LWG:       PLATFORM_1L88,
	}
	MODE_TO_PRODUCT = map[string]string{
		MODE_HLWB:      PRODUCT_HELAN,
		MODE_HLTD:      PRODUCT_HELAN,
		MODE_HLWB_DSDS: PRODUCT_HELAN,
		MODE_HLTD_DSDS: PRODUCT_HELAN,
		MODE_LTG:       PRODUCT_HELANLTE,
		MODE_LWG:       PRODUCT_HELANLTE,
	}
	MODE_TO_PREFIX_LEN = map[string]int{
		MODE_HLWB:      len(HL_ROOT),
		MODE_HLTD:      len(HL_ROOT),
		MODE_HLWB_DSDS: len(HL_DSDS_ROOT),
		MODE_HLTD_DSDS: len(HL_DSDS_ROOT),
		MODE_LTG:       len(LTE_ROOT),
		MODE_LWG:       len(LTE_ROOT),
	}
	MODE_TO_ROOT_PATH = map[string]string{
		MODE_HLWB:      HL_ROOT,
		MODE_HLTD:      HL_ROOT,
		MODE_HLWB_DSDS: HL_DSDS_ROOT,
		MODE_HLTD_DSDS: HL_DSDS_ROOT,
		MODE_LTG:       LTE_ROOT,
		MODE_LWG:       LTE_ROOT,
	}

	MODEL_LIST   = []string{MODEL_1088, MODEL_1T88, MODEL_1L88}
	SIM_LIST     = []string{SIM_SINGLE, SIM_DSDS, SIM_DSDA}
	NETWORK_LIST = []string{NETWORK_LTE, NETWORK_TD, NETWORK_WB}

	FLAG_LIST = []int{DROPPED_FLAG, AVAILABLE_FLAG, DISABLE_FLAG}
)
