package constant

import ()

const (
	//	CP_RELEASE_ROOT = "/home/manson/OTA/LOCAL_RELEASE/"
	CP_RELEASE_ROOT = "/home/manson/OTA/CP_RELEASE/"

	LOGS_ROOT = "/home/manson/OTA/logs/"

	HLWB_ROOT      = CP_RELEASE_ROOT + MODE_HLWB
	HLWB_DSDS_ROOT = CP_RELEASE_ROOT + MODE_HLWB_DSDS
	HLTD_ROOT      = CP_RELEASE_ROOT + MODE_HLTD
	HLTD_DSDS_ROOT = CP_RELEASE_ROOT + MODE_HLTD_DSDS
	LTG_ROOT       = CP_RELEASE_ROOT + MODE_LTG
	LWG_ROOT       = CP_RELEASE_ROOT + MODE_LWG

	MONITOR_COUNT = 5
)

const (
	TABLE_ARBI = "arbi"
	TABLE_GRBI = "grbi"
	TABLE_CP   = "cp_release"
)

const (
	TYPE_SINGLE = "SINGLE"
	TYPE_DSDS   = "DSDS"
	TYPE_DSDA   = "DSDA"

	MODE_HLWB      = "HLWB"
	MODE_HLWB_DSDS = "HLWB_DSDS"
	MODE_HLTD      = "HLTD"
	MODE_HLTD_DSDS = "HLTD_DSDS"
	MODE_LTG       = "LTG"
	MODE_LWG       = "LWG"

	NETWORK_TD  = "TG"
	NETWORK_WB  = "WG"
	NETWORK_LTE = "LTG"

	PLATFORM_1088 = "HELAN"
	PLATFORM_1L88 = "HELANLTE"

	PRODUCT_HELAN    = "pxa1088dkb"
	PRODUCT_HELANLTE = "pxa1L88dkb"

	MODEL_1088 = "pxa1088ff_def"
	MODEL_1T88 = "pxa1t88ff_def"
	MODEL_1L88 = "pxa1l88ff_def"

	DEVICE_FF  = "FF"
	DEVICE_DKB = "DKB"

	DROPPED_FLAG   = -1
	AVAILABLE_FLAG = 1
	DISABLE_FLAG   = 2
)

var (
	PATH_TO_MODE = map[string]string{
		HLWB_ROOT:      MODE_HLWB,
		HLWB_DSDS_ROOT: MODE_HLWB_DSDS,
		HLTD_ROOT:      MODE_HLTD,
		HLTD_DSDS_ROOT: MODE_HLTD_DSDS,
		LTG_ROOT:       MODE_LTG,
		LWG_ROOT:       MODE_LWG,
	}
	MODE_TO_TYPE = map[string]string{
		MODE_HLWB:      TYPE_SINGLE,
		MODE_HLTD:      TYPE_SINGLE,
		MODE_HLWB_DSDS: TYPE_DSDS,
		MODE_HLTD_DSDS: TYPE_DSDS,
		MODE_LTG:       TYPE_SINGLE,
		MODE_LWG:       TYPE_SINGLE,
	}
	MODE_TO_NETWORK = map[string]string{
		MODE_HLWB:      NETWORK_WB,
		MODE_HLTD:      NETWORK_TD,
		MODE_HLWB_DSDS: NETWORK_WB,
		MODE_HLTD_DSDS: NETWORK_TD,
		MODE_LTG:       NETWORK_LTE,
		MODE_LWG:       NETWORK_LTE,
	}
	MODE_TO_PLATFORM = map[string]string{
		MODE_HLWB:      PLATFORM_1088,
		MODE_HLTD:      PLATFORM_1088,
		MODE_HLWB_DSDS: PLATFORM_1088,
		MODE_HLTD_DSDS: PLATFORM_1088,
		MODE_LTG:       PLATFORM_1L88,
		MODE_LWG:       PLATFORM_1L88,
	}
	MODE_TO_PRODUCT = map[string]string{
		MODE_HLWB:      PRODUCT_HELAN,
		MODE_HLTD:      PRODUCT_HELAN,
		MODE_HLWB_DSDS: PRODUCT_HELAN,
		MODE_HLTD_DSDS: PRODUCT_HELAN,
		MODE_LTG:       PRODUCT_HELANLTE,
		MODE_LWG:       PRODUCT_HELANLTE,
	}

	PREFIX_LEN = len(CP_RELEASE_ROOT)

	MODEL_LIST = []string{MODEL_1088, MODEL_1T88, MODEL_1L88}
	TYPE_LIST  = []string{TYPE_SINGLE, TYPE_DSDS, TYPE_DSDA}
	FLAG_LIST  = []int{DROPPED_FLAG, AVAILABLE_FLAG, DISABLE_FLAG}
)
